[opener]
edit = [
	{ run = "${EDITOR:-nvim} %s", desc = "$EDITOR", for = "unix", block = true},
]
open = [
	{ run = "xdg-open %s1", desc = "Open"},
]

[open]
rules = [
	{ mime = "image/*", use = "open"},
]
